data:
  in_memory: 0
  num_workers: 8
dist:
  world_size: 1
model:
  arch: resnet50
resolution:
  end_ramp: 76
  max_res: 192
  min_res: 160
  start_ramp: 65
training:
  batch_size: 512
  bn_wd: 0
  distributed: 0
  epochs: 88
  label_smoothing: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 256